# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/88691/project/hw2_bd/hw2_bd.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/design_1_RGB_LED_0_0.xci
# IP: The module: 'design_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/88691/project/hw2_bd/hw2_bd.srcs/Users/88691/project/RGB_IP/RGB_IP.srcs/constrs_1/imports/xdc/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/88691/project/hw2_bd/hw2_bd.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_0/design_1_RGB_LED_0_0.xci
# IP: The module: 'design_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/88691/project/hw2_bd/hw2_bd.srcs/Users/88691/project/RGB_IP/RGB_IP.srcs/constrs_1/imports/xdc/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
